### ISSUE TITLE
starting with an empty database

### ISSUE THREAD

**Issue by daviddoji** [Technosoft2000/docker-calibre-web#50]
Hi, 
I'm having a small issue configuring the web-interface. I'm running it through a docker-compose file with these parameters:
```
  calibre:
    image: technosoft2000/calibre-web
    container_name: calibre
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    ports:
      - 8083:8083
    volumes:
      - /media/HDD1/Calibre/data/calibre-web:/config
      - /media/HDD1/Calibre/Archive:/books
    labels:
      - traefik.backend=calibre
      - traefik.frontend.rule=Host:mydomain.com
      - traefik.port=8083
      - traefik.enable=true
```
And the .env file with these parameters:
```
# Calibre-web
USE_CONFIG_DIR=true
SET_CONTAINER_TIMEZONE=true
CONTAINER_TIMEZONE=Europe/Madrid
PUID=1000
PGID=1000
```
As you can see, I've created a metadata.db externally and a book was added. This the where I'm mounting the database and books in /media/HDD1/Calibre:
```
├── Archive
│   ├── Megan Shisler
│   │   └── NumPy Cookbook (1)
│   │       ├── cover.jpg
│   │       ├── metadata.opf
│   │       └── NumPy Cookbook - Megan Shisler.pdf
│   └── metadata.db
└── data
    └── calibre-web
```
The problem comes at the web-interface. It asks me about the location of my calibre database, but it doesn't accept:
`/media/HDD1/Calibre/Archive`

What am I doing wrong?

Thanks for your help.
