### ISSUE TITLE
DB location is not valid, please enter correct path

### ISSUE THREAD

**Issue by luther84** [Technosoft2000/docker-calibre-web#58]
I'm very sorry for opening another ticket about this error message but I feel like I am taking crazy pills. No matter what I've tried I cannot get past the config screen, calibre-web will not accept my metadata.db location. I believe I have set permissions properly, I have tried several variations on db location, permissioning and setup.

The version of Calibre that I used to create the db is 3.42.0

docker-compose.yml
```
  calibre-web:
    container_name: calibre-web
    restart: unless-stopped
    image: technosoft2000/calibre-web
    volumes:
      - /share/CACHEDEV1_DATA/Public/Books:/books
      - /share/CACHEDEV1_DATA/Container/Homelab/calibre-web/config:/config
    environment:
      - PGID=1001
      - PUID=1000
      - USE_CONFIG_DIR=true
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=America/New_York
    ports:
      - "8083:8083"
    labels:
      - "traefik.enable=false"
```

Output of `docker exec -it calibre-web ls -l /books/metadata.db`
`-rwxrwxrwx+ 1 root calibre 389120 May  4 23:33 /books/metadata.db`

Here's the output of `docker logs calibre-web`
[pastebin link](https://pastebin.com/0JJnY3zR)

**Comment by Technosoft2000** [comment]
Hi @luther84 ,

at the first look I can't see any issue at the log files and delivered info, everything looks okay.
But as you wrote I see at the log file that you stuck at the config page and I've no idea now why it happens :-o

At your calibre app directory (inside the docker container) you should have also a `calibre.log` file - could you please check this one if you can see any issue there and please provide the content of it so that I can check it too :)

You've also the possibility to map the app directory as volume while container creation:
`-v <your Calibre Web application folder>:/calibre-web/app`

**Comment by luther84** [comment]
Thanks for taking a look! I really appreciate it. I have slightly modified the docker-compose and included it below. I fixed the internal folder for the config directory, added a depends for the proxy container and mounted the app folder. I still cannot get past the config page. No entry I put in `Location of Calibre database` is accepted. As far as I can see elsewhere `/books` should be accepted with my config.

```
   calibre-web:
    container_name: calibre-web
    restart: unless-stopped
    image: technosoft2000/calibre-web
    depends_on:
      - "reverse-proxy"
    volumes:
      - /share/CACHEDEV1_DATA/Public/Books:/books
      - /share/CACHEDEV1_DATA/Container/Homelab/calibre-web/config:/calibre-web/config
      - /share/CACHEDEV1_DATA/Container/Homelab/calibre-web/app:/calibre-web/app
    environment:
      - PGID=1001
      - PUID=1000
      - USE_CONFIG_DIR=true
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=America/New_York
    ports:
      - "8083:8083"
    labels:
      - "traefik.enable=false"
```

Here is output of `docker exec -it calibre-web ls -l /books/metadata.db`
`-rwxrwxrwx+ 1 root calibre 389120 May  5 00:34 /books/metadata.db`

pastebin of `docker logs calibre-web` (the POST towards the end is my last attempt to submit /books as the Calibre db location)
https://pastebin.com/1tpNdP7x

pastbin of the logfiles `/app/calibre-web.log` and `/config/calibre-web.log`
https://pastebin.com/dT8fMp3M

Still not seeing anything obvious, looking through the code I appear to be failing a db.setup_db function but I'm not certain. Is there a way I could bump the log level?

Is there any other information that would be useful?
